[2024-02-06T19:03:41.681+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyDag.ingest_data_task scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-02-06T19:03:41.688+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyDag.ingest_data_task scheduled__2024-01-06T00:00:00+00:00 [queued]>
[2024-02-06T19:03:41.689+0100] {taskinstance.py:2171} INFO - Starting attempt 2 of 2
[2024-02-06T19:03:41.762+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2024-01-06 00:00:00+00:00
[2024-02-06T19:03:41.772+0100] {standard_task_runner.py:60} INFO - Started process 6895 to run task
[2024-02-06T19:03:41.777+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'MyDag', 'ingest_data_task', 'scheduled__2024-01-06T00:00:00+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/FilmDag.py', '--cfg-path', '/tmp/tmpr14dd2ml']
[2024-02-06T19:03:41.782+0100] {standard_task_runner.py:88} INFO - Job 67: Subtask ingest_data_task
[2024-02-06T19:03:41.828+0100] {task_command.py:423} INFO - Running <TaskInstance: MyDag.ingest_data_task scheduled__2024-01-06T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-06T19:03:41.887+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='MyDag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-06T00:00:00+00:00'
[2024-02-06T19:04:58.100+0100] {logging_mixin.py:188} INFO - Erreur de requÃªte: 400
[2024-02-06T19:04:58.102+0100] {logging_mixin.py:188} INFO - {"success":false,"status_code":22,"status_message":"Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."}
[2024-02-06T19:04:58.105+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/program.py", line 76, in ingest_data
    movies_data()
  File "/home/ubuntu/airflow/dags/program.py", line 58, in movies_data
    with open(popular_movies_json_file_path, 'w', encoding='utf-8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/user/datalakefilm/films/all_popular_movies.json'
[2024-02-06T19:04:58.111+0100] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=MyDag, task_id=ingest_data_task, execution_date=20240106T000000, start_date=20240206T180341, end_date=20240206T180458
[2024-02-06T19:04:58.138+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 67 for task ingest_data_task ([Errno 2] No such file or directory: '/user/datalakefilm/films/all_popular_movies.json'; 6895)
[2024-02-06T19:04:58.164+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T19:04:58.178+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
