[2024-02-02T16:38:59.943+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyDag.ingest_data_task scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-02-02T16:38:59.958+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyDag.ingest_data_task scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-02-02T16:38:59.959+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-02T16:39:00.006+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): ingest_data_task> on 2024-01-04 00:00:00+00:00
[2024-02-02T16:39:00.022+0100] {standard_task_runner.py:60} INFO - Started process 12235 to run task
[2024-02-02T16:39:00.030+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'MyDag', 'ingest_data_task', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/FilmDag.py', '--cfg-path', '/tmp/tmppx9ma6ns']
[2024-02-02T16:39:00.040+0100] {standard_task_runner.py:88} INFO - Job 46: Subtask ingest_data_task
[2024-02-02T16:39:00.132+0100] {task_command.py:423} INFO - Running <TaskInstance: MyDag.ingest_data_task scheduled__2024-01-04T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-02T16:39:00.252+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='MyDag' AIRFLOW_CTX_TASK_ID='ingest_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2024-02-02T16:40:46.736+0100] {logging_mixin.py:188} INFO - Erreur de requÃªte: 400
[2024-02-02T16:40:46.737+0100] {logging_mixin.py:188} INFO - {"success":false,"status_code":22,"status_message":"Invalid page: Pages start at 1 and max at 500. They are expected to be an integer."}
[2024-02-02T16:40:46.740+0100] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ubuntu/airflow/dags/program.py", line 76, in ingest_data
    movies_data()
  File "/home/ubuntu/airflow/dags/program.py", line 58, in movies_data
    with open(popular_movies_json_file_path, 'w', encoding='utf-8') as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/user/datalakefilm/films/all_popular_movies.json'
[2024-02-02T16:40:46.746+0100] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=MyDag, task_id=ingest_data_task, execution_date=20240104T000000, start_date=20240202T153859, end_date=20240202T154046
[2024-02-02T16:40:46.773+0100] {standard_task_runner.py:107} ERROR - Failed to execute job 46 for task ingest_data_task ([Errno 2] No such file or directory: '/user/datalakefilm/films/all_popular_movies.json'; 12235)
[2024-02-02T16:40:46.793+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-02T16:40:46.806+0100] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
